build:
  name: OpenSearch
  version: 1.1.1
components:
- checks:
  - gradle:publish
  - gradle:properties:version
  name: OpenSearch
  ref: '1.1'
  repository: https://github.com/opensearch-project/OpenSearch.git
schema-version: '1.0'
